package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFirsttype<M extends BaseFirsttype<M>> extends Model<M> implements IBean {

	public M setFirstTypeId(java.lang.String firstTypeId) {
		set("first_type_id", firstTypeId);
		return (M)this;
	}
	
	public java.lang.String getFirstTypeId() {
		return getStr("first_type_id");
	}

	public M setFirstTypeName(java.lang.String firstTypeName) {
		set("first_type_name", firstTypeName);
		return (M)this;
	}
	
	public java.lang.String getFirstTypeName() {
		return getStr("first_type_name");
	}

}
