package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbSecType<M extends BaseTbSecType<M>> extends Model<M> implements IBean {

	public M setSecTypeId(java.lang.String secTypeId) {
		set("sec_type_id", secTypeId);
		return (M)this;
	}
	
	public java.lang.String getSecTypeId() {
		return getStr("sec_type_id");
	}

	public M setFirstTypeId(java.lang.String firstTypeId) {
		set("first_type_id", firstTypeId);
		return (M)this;
	}
	
	public java.lang.String getFirstTypeId() {
		return getStr("first_type_id");
	}

	public M setSecTypeName(java.lang.String secTypeName) {
		set("sec_type_name", secTypeName);
		return (M)this;
	}
	
	public java.lang.String getSecTypeName() {
		return getStr("sec_type_name");
	}

}
