package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbWxMenu2<M extends BaseTbWxMenu2<M>> extends Model<M> implements IBean {

	public M setWxMenu2Id(java.lang.Integer wxMenu2Id) {
		set("wx_menu2_id", wxMenu2Id);
		return (M)this;
	}
	
	public java.lang.Integer getWxMenu2Id() {
		return getInt("wx_menu2_id");
	}

	public M setWxMenu1Id(java.lang.Integer wxMenu1Id) {
		set("wx_menu1_id", wxMenu1Id);
		return (M)this;
	}
	
	public java.lang.Integer getWxMenu1Id() {
		return getInt("wx_menu1_id");
	}

	public M setWxMenu2Name(java.lang.String wxMenu2Name) {
		set("wx_menu2_name", wxMenu2Name);
		return (M)this;
	}
	
	public java.lang.String getWxMenu2Name() {
		return getStr("wx_menu2_name");
	}

	public M setWxMenu2Type(java.lang.String wxMenu2Type) {
		set("wx_menu2_type", wxMenu2Type);
		return (M)this;
	}
	
	public java.lang.String getWxMenu2Type() {
		return getStr("wx_menu2_type");
	}

	public M setWxMenu2Url(java.lang.String wxMenu2Url) {
		set("wx_menu2_url", wxMenu2Url);
		return (M)this;
	}
	
	public java.lang.String getWxMenu2Url() {
		return getStr("wx_menu2_url");
	}

}
