package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseOrderDetail<M extends BaseOrderDetail<M>> extends Model<M> implements IBean {

	public M setOrderId(java.lang.String orderId) {
		set("order_id", orderId);
		return (M)this;
	}
	
	public java.lang.String getOrderId() {
		return getStr("order_id");
	}

	public M setShopId(java.lang.String shopId) {
		set("shop_id", shopId);
		return (M)this;
	}
	
	public java.lang.String getShopId() {
		return getStr("shop_id");
	}

	public M setOrderDetailNum(java.lang.Integer orderDetailNum) {
		set("order_detail_num", orderDetailNum);
		return (M)this;
	}
	
	public java.lang.Integer getOrderDetailNum() {
		return getInt("order_detail_num");
	}

	public M setOrderDetailId(java.lang.String orderDetailId) {
		set("order_detail_id", orderDetailId);
		return (M)this;
	}
	
	public java.lang.String getOrderDetailId() {
		return getStr("order_detail_id");
	}

}
