package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbRecruitInfo<M extends BaseTbRecruitInfo<M>> extends Model<M> implements IBean {

	public M setRid(java.lang.Integer rid) {
		set("rid", rid);
		return (M)this;
	}
	
	public java.lang.Integer getRid() {
		return getInt("rid");
	}

	public M setPostion(java.lang.String postion) {
		set("postion", postion);
		return (M)this;
	}
	
	public java.lang.String getPostion() {
		return getStr("postion");
	}

	public M setRealseTime(java.util.Date realseTime) {
		set("realse_time", realseTime);
		return (M)this;
	}
	
	public java.util.Date getRealseTime() {
		return get("realse_time");
	}

	public M setExperice(java.lang.String experice) {
		set("experice", experice);
		return (M)this;
	}
	
	public java.lang.String getExperice() {
		return getStr("experice");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}
	
	public java.lang.String getCategory() {
		return getStr("category");
	}

	public M setEducation(java.lang.String education) {
		set("education", education);
		return (M)this;
	}
	
	public java.lang.String getEducation() {
		return getStr("education");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setCompany(java.lang.String company) {
		set("company", company);
		return (M)this;
	}
	
	public java.lang.String getCompany() {
		return getStr("company");
	}

	public M setWorkpalce(java.lang.String workpalce) {
		set("workpalce", workpalce);
		return (M)this;
	}
	
	public java.lang.String getWorkpalce() {
		return getStr("workpalce");
	}

	public M setNumber(java.lang.Integer number) {
		set("number", number);
		return (M)this;
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public M setValidity(java.util.Date Validity) {
		set("Validity", Validity);
		return (M)this;
	}
	
	public java.util.Date getValidity() {
		return get("Validity");
	}

}
