package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public M setMessageId(java.lang.String messageId) {
		set("message_id", messageId);
		return (M)this;
	}
	
	public java.lang.String getMessageId() {
		return getStr("message_id");
	}

	public M setMessageSender(java.lang.String messageSender) {
		set("message_sender", messageSender);
		return (M)this;
	}
	
	public java.lang.String getMessageSender() {
		return getStr("message_sender");
	}

	public M setMessageReceiver(java.lang.String messageReceiver) {
		set("message_receiver", messageReceiver);
		return (M)this;
	}
	
	public java.lang.String getMessageReceiver() {
		return getStr("message_receiver");
	}

	public M setMessageType(java.lang.Boolean messageType) {
		set("message_type", messageType);
		return (M)this;
	}
	
	public java.lang.Boolean getMessageType() {
		return get("message_type");
	}

	public M setMessageContent(java.lang.String messageContent) {
		set("message_content", messageContent);
		return (M)this;
	}
	
	public java.lang.String getMessageContent() {
		return getStr("message_content");
	}

	public M setMessageSendTime(java.util.Date messageSendTime) {
		set("message_send_time", messageSendTime);
		return (M)this;
	}
	
	public java.util.Date getMessageSendTime() {
		return get("message_send_time");
	}

	public M setMessageName(java.lang.String messageName) {
		set("message_name", messageName);
		return (M)this;
	}
	
	public java.lang.String getMessageName() {
		return getStr("message_name");
	}

}
