package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoleNavigation<M extends BaseRoleNavigation<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setRoleId(java.lang.String roleId) {
		set("roleId", roleId);
		return (M)this;
	}
	
	public java.lang.String getRoleId() {
		return getStr("roleId");
	}

	public M setNavigationId(java.lang.String navigationId) {
		set("navigationId", navigationId);
		return (M)this;
	}
	
	public java.lang.String getNavigationId() {
		return getStr("navigationId");
	}

}
