package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbPaigongOrder<M extends BaseTbPaigongOrder<M>> extends Model<M> implements IBean {

	public M setForwardId(java.lang.Integer forwardId) {
		set("forward_id", forwardId);
		return (M)this;
	}
	
	public java.lang.Integer getForwardId() {
		return getInt("forward_id");
	}

	public M setServiceOrderId(java.lang.Integer serviceOrderId) {
		set("service_order_id", serviceOrderId);
		return (M)this;
	}
	
	public java.lang.Integer getServiceOrderId() {
		return getInt("service_order_id");
	}

	public M setForwardTime(java.util.Date forwardTime) {
		set("forward_time", forwardTime);
		return (M)this;
	}
	
	public java.util.Date getForwardTime() {
		return get("forward_time");
	}

}
