package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbMuser<M extends BaseTbMuser<M>> extends Model<M> implements IBean {

	public M setMid(java.lang.String mid) {
		set("mid", mid);
		return (M)this;
	}
	
	public java.lang.String getMid() {
		return getStr("mid");
	}

	public M setMname(java.lang.String mname) {
		set("mname", mname);
		return (M)this;
	}
	
	public java.lang.String getMname() {
		return getStr("mname");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setSex(java.lang.Integer sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setKindlog(java.lang.String kindlog) {
		set("kindlog", kindlog);
		return (M)this;
	}
	
	public java.lang.String getKindlog() {
		return getStr("kindlog");
	}

	public M setLog(java.lang.String log) {
		set("log", log);
		return (M)this;
	}
	
	public java.lang.String getLog() {
		return getStr("log");
	}

	public M setMpassword(java.lang.String mpassword) {
		set("mpassword", mpassword);
		return (M)this;
	}
	
	public java.lang.String getMpassword() {
		return getStr("mpassword");
	}

	public M setMrealname(java.lang.String mrealname) {
		set("mrealname", mrealname);
		return (M)this;
	}
	
	public java.lang.String getMrealname() {
		return getStr("mrealname");
	}

}
