package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbRentTools<M extends BaseTbRentTools<M>> extends Model<M> implements IBean {

	public M setTid(java.lang.Integer tid) {
		set("tid", tid);
		return (M)this;
	}
	
	public java.lang.Integer getTid() {
		return getInt("tid");
	}

	public M setTypId(java.lang.Integer typId) {
		set("typ_id", typId);
		return (M)this;
	}
	
	public java.lang.Integer getTypId() {
		return getInt("typ_id");
	}

	public M setNameT(java.lang.String nameT) {
		set("name_t", nameT);
		return (M)this;
	}
	
	public java.lang.String getNameT() {
		return getStr("name_t");
	}

	public M setTypeT(java.lang.String typeT) {
		set("type_t", typeT);
		return (M)this;
	}
	
	public java.lang.String getTypeT() {
		return getStr("type_t");
	}

	public M setAddressTid(java.lang.Integer addressTid) {
		set("address_tid", addressTid);
		return (M)this;
	}
	
	public java.lang.Integer getAddressTid() {
		return getInt("address_tid");
	}

	public M setContact(java.lang.String contact) {
		set("contact", contact);
		return (M)this;
	}
	
	public java.lang.String getContact() {
		return getStr("contact");
	}

	public M setPhoneT(java.lang.String phoneT) {
		set("phone_t", phoneT);
		return (M)this;
	}
	
	public java.lang.String getPhoneT() {
		return getStr("phone_t");
	}

	public M setPalce(java.lang.String palce) {
		set("palce", palce);
		return (M)this;
	}
	
	public java.lang.String getPalce() {
		return getStr("palce");
	}

	public M setTPrice(java.lang.Float tPrice) {
		set("t_price", tPrice);
		return (M)this;
	}
	
	public java.lang.Float getTPrice() {
		return getFloat("t_price");
	}

}
