package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbMuser<M extends BaseTbMuser<M>> extends Model<M> implements IBean {

	public M setMid(java.lang.Integer mid) {
		set("mid", mid);
		return (M)this;
	}
	
	public java.lang.Integer getMid() {
		return getInt("mid");
	}

	public M setMuser(java.lang.String muser) {
		set("muser", muser);
		return (M)this;
	}
	
	public java.lang.String getMuser() {
		return getStr("muser");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setCredit(java.lang.Integer credit) {
		set("credit", credit);
		return (M)this;
	}
	
	public java.lang.Integer getCredit() {
		return getInt("credit");
	}

	public M setMType(java.lang.String mType) {
		set("m_type", mType);
		return (M)this;
	}
	
	public java.lang.String getMType() {
		return getStr("m_type");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

}
