package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePactEmploy<M extends BasePactEmploy<M>> extends Model<M> implements IBean {

	public M setPemId(java.lang.String pemId) {
		set("pem_id", pemId);
		return (M)this;
	}
	
	public java.lang.String getPemId() {
		return getStr("pem_id");
	}

	public M setRid(java.lang.String rid) {
		set("rid", rid);
		return (M)this;
	}
	
	public java.lang.String getRid() {
		return getStr("rid");
	}

	public M setMid(java.lang.String mid) {
		set("mid", mid);
		return (M)this;
	}
	
	public java.lang.String getMid() {
		return getStr("mid");
	}

	public M setPeStime(java.util.Date peStime) {
		set("pe_stime", peStime);
		return (M)this;
	}
	
	public java.util.Date getPeStime() {
		return get("pe_stime");
	}

	public M setPeEtime(java.util.Date peEtime) {
		set("pe_etime", peEtime);
		return (M)this;
	}
	
	public java.util.Date getPeEtime() {
		return get("pe_etime");
	}

	public M setPeState(java.lang.Integer peState) {
		set("pe_state", peState);
		return (M)this;
	}
	
	public java.lang.Integer getPeState() {
		return getInt("pe_state");
	}

	public M setPreIncome(java.lang.Float preIncome) {
		set("pre_income", preIncome);
		return (M)this;
	}
	
	public java.lang.Float getPreIncome() {
		return getFloat("pre_income");
	}

}
