package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseManager<M extends BaseManager<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
		return (M)this;
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("createDate", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("createDate");
	}

	public M setModifyDate(java.util.Date modifyDate) {
		set("modifyDate", modifyDate);
		return (M)this;
	}
	
	public java.util.Date getModifyDate() {
		return get("modifyDate");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setIsAccountEnabled(java.lang.Boolean isAccountEnabled) {
		set("isAccountEnabled", isAccountEnabled);
		return (M)this;
	}
	
	public java.lang.Boolean getIsAccountEnabled() {
		return get("isAccountEnabled");
	}

	public M setIsAccountExpired(java.lang.Boolean isAccountExpired) {
		set("isAccountExpired", isAccountExpired);
		return (M)this;
	}
	
	public java.lang.Boolean getIsAccountExpired() {
		return get("isAccountExpired");
	}

	public M setIsAccountLocked(java.lang.Boolean isAccountLocked) {
		set("isAccountLocked", isAccountLocked);
		return (M)this;
	}
	
	public java.lang.Boolean getIsAccountLocked() {
		return get("isAccountLocked");
	}

	public M setIsCredentialsExpired(java.lang.Boolean isCredentialsExpired) {
		set("isCredentialsExpired", isCredentialsExpired);
		return (M)this;
	}
	
	public java.lang.Boolean getIsCredentialsExpired() {
		return get("isCredentialsExpired");
	}

	public M setLockedDate(java.util.Date lockedDate) {
		set("lockedDate", lockedDate);
		return (M)this;
	}
	
	public java.util.Date getLockedDate() {
		return get("lockedDate");
	}

	public M setLoginDate(java.util.Date loginDate) {
		set("loginDate", loginDate);
		return (M)this;
	}
	
	public java.util.Date getLoginDate() {
		return get("loginDate");
	}

	public M setLoginFailureCount(java.lang.Integer loginFailureCount) {
		set("loginFailureCount", loginFailureCount);
		return (M)this;
	}
	
	public java.lang.Integer getLoginFailureCount() {
		return getInt("loginFailureCount");
	}

	public M setLoginIp(java.lang.String loginIp) {
		set("loginIp", loginIp);
		return (M)this;
	}
	
	public java.lang.String getLoginIp() {
		return getStr("loginIp");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

}
