package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbCity<M extends BaseTbCity<M>> extends Model<M> implements IBean {

	public M setCityId(java.lang.String cityId) {
		set("city_id", cityId);
		return (M)this;
	}
	
	public java.lang.String getCityId() {
		return getStr("city_id");
	}

	public M setProvinceId(java.lang.String provinceId) {
		set("province_id", provinceId);
		return (M)this;
	}
	
	public java.lang.String getProvinceId() {
		return getStr("province_id");
	}

	public M setCityName(java.lang.String cityName) {
		set("city_name", cityName);
		return (M)this;
	}
	
	public java.lang.String getCityName() {
		return getStr("city_name");
	}

}
