package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbUser<M extends BaseTbUser<M>> extends Model<M> implements IBean {

	public M setOpenid(java.lang.String openid) {
		set("openid", openid);
		return (M)this;
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}
	
	public java.lang.String getSex() {
		return getStr("sex");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public M setDetailadd(java.lang.String detailadd) {
		set("detailadd", detailadd);
		return (M)this;
	}
	
	public java.lang.String getDetailadd() {
		return getStr("detailadd");
	}

	public M setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
		return (M)this;
	}
	
	public java.lang.String getHeadimgurl() {
		return getStr("headimgurl");
	}

}
