package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseService<M extends BaseService<M>> extends Model<M> implements IBean {

	public M setServiceId(java.lang.Integer serviceId) {
		set("service_id", serviceId);
		return (M)this;
	}
	
	public java.lang.Integer getServiceId() {
		return getInt("service_id");
	}

	public M setServiceName(java.lang.String serviceName) {
		set("service_name", serviceName);
		return (M)this;
	}
	
	public java.lang.String getServiceName() {
		return getStr("service_name");
	}

	public M setServicePrice(java.lang.Float servicePrice) {
		set("service_price", servicePrice);
		return (M)this;
	}
	
	public java.lang.Float getServicePrice() {
		return getFloat("service_price");
	}

	public M setAttribute32(java.lang.String attribute32) {
		set("Attribute_32", attribute32);
		return (M)this;
	}
	
	public java.lang.String getAttribute32() {
		return getStr("Attribute_32");
	}

}
