package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseManagerRole<M extends BaseManagerRole<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.String getId() {
		return getStr("id");
	}

	public M setManagerId(java.lang.String managerId) {
		set("managerId", managerId);
		return (M)this;
	}
	
	public java.lang.String getManagerId() {
		return getStr("managerId");
	}

	public M setRoleId(java.lang.String roleId) {
		set("roleId", roleId);
		return (M)this;
	}
	
	public java.lang.String getRoleId() {
		return getStr("roleId");
	}

}
