package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAnnouncement<M extends BaseAnnouncement<M>> extends Model<M> implements IBean {

	public M setAnnouncementId(java.lang.String announcementId) {
		set("announcement_id", announcementId);
		return (M)this;
	}
	
	public java.lang.String getAnnouncementId() {
		return getStr("announcement_id");
	}

	public M setAnnouncementTittle(java.lang.String announcementTittle) {
		set("announcement_tittle", announcementTittle);
		return (M)this;
	}
	
	public java.lang.String getAnnouncementTittle() {
		return getStr("announcement_tittle");
	}

	public M setAnnouncementImg(java.lang.String announcementImg) {
		set("announcement_img", announcementImg);
		return (M)this;
	}
	
	public java.lang.String getAnnouncementImg() {
		return getStr("announcement_img");
	}

	public M setAnnouncementUrl(java.lang.String announcementUrl) {
		set("announcement_url", announcementUrl);
		return (M)this;
	}
	
	public java.lang.String getAnnouncementUrl() {
		return getStr("announcement_url");
	}

	public M setAnnouncementOn(java.lang.Boolean announcementOn) {
		set("announcement_on", announcementOn);
		return (M)this;
	}
	
	public java.lang.Boolean getAnnouncementOn() {
		return get("announcement_on");
	}

}
