package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbRealshop<M extends BaseTbRealshop<M>> extends Model<M> implements IBean {

	public M setRealshopId(java.lang.String realshopId) {
		set("realshop_id", realshopId);
		return (M)this;
	}
	
	public java.lang.String getRealshopId() {
		return getStr("realshop_id");
	}

	public M setRealshopName(java.lang.String realshopName) {
		set("realshop_name", realshopName);
		return (M)this;
	}
	
	public java.lang.String getRealshopName() {
		return getStr("realshop_name");
	}

	public M setDistrictId(java.lang.String districtId) {
		set("district_id", districtId);
		return (M)this;
	}
	
	public java.lang.String getDistrictId() {
		return getStr("district_id");
	}

	public M setRealshopPhone(java.lang.String realshopPhone) {
		set("realshop_phone", realshopPhone);
		return (M)this;
	}
	
	public java.lang.String getRealshopPhone() {
		return getStr("realshop_phone");
	}

	public M setRealshopPic(java.lang.String realshopPic) {
		set("realshop_pic", realshopPic);
		return (M)this;
	}
	
	public java.lang.String getRealshopPic() {
		return getStr("realshop_pic");
	}

	public M setRealshopDetailAddress(java.lang.String realshopDetailAddress) {
		set("realshop_detail_address", realshopDetailAddress);
		return (M)this;
	}
	
	public java.lang.String getRealshopDetailAddress() {
		return getStr("realshop_detail_address");
	}

	public M setRealshopType(java.lang.String realshopType) {
		set("realshop_type", realshopType);
		return (M)this;
	}
	
	public java.lang.String getRealshopType() {
		return getStr("realshop_type");
	}

}
