package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setUserOpenid(java.lang.String userOpenid) {
		set("user_openid", userOpenid);
		return (M)this;
	}
	
	public java.lang.String getUserOpenid() {
		return getStr("user_openid");
	}

	public M setUserNickname(java.lang.String userNickname) {
		set("user_nickname", userNickname);
		return (M)this;
	}
	
	public java.lang.String getUserNickname() {
		return getStr("user_nickname");
	}

	public M setUserAge(java.lang.Integer userAge) {
		set("user_age", userAge);
		return (M)this;
	}
	
	public java.lang.Integer getUserAge() {
		return getInt("user_age");
	}

	public M setUserSex(java.lang.String userSex) {
		set("user_sex", userSex);
		return (M)this;
	}
	
	public java.lang.String getUserSex() {
		return getStr("user_sex");
	}

	public M setUserPhone(java.lang.String userPhone) {
		set("user_phone", userPhone);
		return (M)this;
	}
	
	public java.lang.String getUserPhone() {
		return getStr("user_phone");
	}

	public M setUserHeadimage(java.lang.String userHeadimage) {
		set("user_headimage", userHeadimage);
		return (M)this;
	}
	
	public java.lang.String getUserHeadimage() {
		return getStr("user_headimage");
	}

	public M setUserAddDetail(java.lang.String userAddDetail) {
		set("user_add_detail", userAddDetail);
		return (M)this;
	}
	
	public java.lang.String getUserAddDetail() {
		return getStr("user_add_detail");
	}

	public M setDistrictId(java.lang.String districtId) {
		set("district_id", districtId);
		return (M)this;
	}
	
	public java.lang.String getDistrictId() {
		return getStr("district_id");
	}

}
