package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePointsGift<M extends BasePointsGift<M>> extends Model<M> implements IBean {

	public M setPointsGiftId(java.lang.String pointsGiftId) {
		set("points_gift_id", pointsGiftId);
		return (M)this;
	}
	
	public java.lang.String getPointsGiftId() {
		return getStr("points_gift_id");
	}

	public M setPointsGiftName(java.lang.String pointsGiftName) {
		set("points_gift_name", pointsGiftName);
		return (M)this;
	}
	
	public java.lang.String getPointsGiftName() {
		return getStr("points_gift_name");
	}

	public M setPointsGiftPoints(java.lang.Integer pointsGiftPoints) {
		set("points_gift_points", pointsGiftPoints);
		return (M)this;
	}
	
	public java.lang.Integer getPointsGiftPoints() {
		return getInt("points_gift_points");
	}

	public M setPointsGiftHeadline(java.util.Date pointsGiftHeadline) {
		set("points_gift_headline", pointsGiftHeadline);
		return (M)this;
	}
	
	public java.util.Date getPointsGiftHeadline() {
		return get("points_gift_headline");
	}

	public M setPointsGiftImg(java.lang.String pointsGiftImg) {
		set("points_gift_img", pointsGiftImg);
		return (M)this;
	}
	
	public java.lang.String getPointsGiftImg() {
		return getStr("points_gift_img");
	}

	public M setPointsGiftIson(java.lang.Boolean pointsGiftIson) {
		set("points_gift_ison", pointsGiftIson);
		return (M)this;
	}
	
	public java.lang.Boolean getPointsGiftIson() {
		return get("points_gift_ison");
	}

	public M setPointsGiftDesc(java.lang.String pointsGiftDesc) {
		set("points_gift_desc", pointsGiftDesc);
		return (M)this;
	}
	
	public java.lang.String getPointsGiftDesc() {
		return getStr("points_gift_desc");
	}

	public M setPointsGiftVol(java.lang.Integer pointsGiftVol) {
		set("points_gift_vol", pointsGiftVol);
		return (M)this;
	}
	
	public java.lang.Integer getPointsGiftVol() {
		return getInt("points_gift_vol");
	}

}
