package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDispatch<M extends BaseTbDispatch<M>> extends Model<M> implements IBean {

	public M setPacId(java.lang.Integer pacId) {
		set("pac_id", pacId);
		return (M)this;
	}
	
	public java.lang.Integer getPacId() {
		return getInt("pac_id");
	}

	public M setMid(java.lang.Integer mid) {
		set("mid", mid);
		return (M)this;
	}
	
	public java.lang.Integer getMid() {
		return getInt("mid");
	}

	public M setServiceOrderId(java.lang.Integer serviceOrderId) {
		set("service_order_id", serviceOrderId);
		return (M)this;
	}
	
	public java.lang.Integer getServiceOrderId() {
		return getInt("service_order_id");
	}

	public M setPacStime(java.util.Date pacStime) {
		set("pac_stime", pacStime);
		return (M)this;
	}
	
	public java.util.Date getPacStime() {
		return get("pac_stime");
	}

	public M setPacEtime(java.util.Date pacEtime) {
		set("pac_etime", pacEtime);
		return (M)this;
	}
	
	public java.util.Date getPacEtime() {
		return get("pac_etime");
	}

}
