package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbMstaff<M extends BaseTbMstaff<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setSpostion(java.lang.String spostion) {
		set("spostion", spostion);
		return (M)this;
	}
	
	public java.lang.String getSpostion() {
		return getStr("spostion");
	}

	public M setStime(java.util.Date stime) {
		set("stime", stime);
		return (M)this;
	}
	
	public java.util.Date getStime() {
		return get("stime");
	}

	public M setSalary(java.lang.String salary) {
		set("salary", salary);
		return (M)this;
	}
	
	public java.lang.String getSalary() {
		return getStr("salary");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public M setSkind(java.lang.String skind) {
		set("skind", skind);
		return (M)this;
	}
	
	public java.lang.String getSkind() {
		return getStr("skind");
	}

	public M setRequire(java.lang.String require) {
		set("require", require);
		return (M)this;
	}
	
	public java.lang.String getRequire() {
		return getStr("require");
	}

	public M setSaddress(java.lang.String saddress) {
		set("saddress", saddress);
		return (M)this;
	}
	
	public java.lang.String getSaddress() {
		return getStr("saddress");
	}

	public M setScontacts(java.lang.String scontacts) {
		set("scontacts", scontacts);
		return (M)this;
	}
	
	public java.lang.String getScontacts() {
		return getStr("scontacts");
	}

	public M setSendtime(java.util.Date sendtime) {
		set("sendtime", sendtime);
		return (M)this;
	}
	
	public java.util.Date getSendtime() {
		return get("sendtime");
	}

}
