package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbDistrict<M extends BaseTbDistrict<M>> extends Model<M> implements IBean {

	public M setDistrictId(java.lang.String districtId) {
		set("district_id", districtId);
		return (M)this;
	}
	
	public java.lang.String getDistrictId() {
		return getStr("district_id");
	}

	public M setCityId(java.lang.String cityId) {
		set("city_id", cityId);
		return (M)this;
	}
	
	public java.lang.String getCityId() {
		return getStr("city_id");
	}

	public M setDistrictName(java.lang.String districtName) {
		set("district_name", districtName);
		return (M)this;
	}
	
	public java.lang.String getDistrictName() {
		return getStr("district_name");
	}

}
