package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbGoods<M extends BaseTbGoods<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTittle(java.lang.String tittle) {
		set("tittle", tittle);
		return (M)this;
	}
	
	public java.lang.String getTittle() {
		return getStr("tittle");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	public java.lang.String getDescription() {
		return getStr("description");
	}

	public M setDetailDescription(java.lang.String detailDescription) {
		set("detail_description", detailDescription);
		return (M)this;
	}
	
	public java.lang.String getDetailDescription() {
		return getStr("detail_description");
	}

	public M setPrice(java.lang.Float price) {
		set("price", price);
		return (M)this;
	}
	
	public java.lang.Float getPrice() {
		return getFloat("price");
	}

	public M setRemain(java.lang.Integer remain) {
		set("remain", remain);
		return (M)this;
	}
	
	public java.lang.Integer getRemain() {
		return getInt("remain");
	}

	public M setHideFlag(java.lang.Boolean hideFlag) {
		set("hide_flag", hideFlag);
		return (M)this;
	}
	
	public java.lang.Boolean getHideFlag() {
		return get("hide_flag");
	}

	public M setCoverimgurl(java.lang.String coverimgurl) {
		set("coverimgurl", coverimgurl);
		return (M)this;
	}
	
	public java.lang.String getCoverimgurl() {
		return getStr("coverimgurl");
	}

	public M setSalesVolume(java.lang.Integer salesVolume) {
		set("sales_volume", salesVolume);
		return (M)this;
	}
	
	public java.lang.Integer getSalesVolume() {
		return getInt("sales_volume");
	}

	public M setScore(java.lang.Float score) {
		set("score", score);
		return (M)this;
	}
	
	public java.lang.Float getScore() {
		return getFloat("score");
	}

}
