package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbMtools<M extends BaseTbMtools<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setTname(java.lang.String tname) {
		set("tname", tname);
		return (M)this;
	}
	
	public java.lang.String getTname() {
		return getStr("tname");
	}

	public M setTkind(java.lang.String tkind) {
		set("tkind", tkind);
		return (M)this;
	}
	
	public java.lang.String getTkind() {
		return getStr("tkind");
	}

	public M setTprice(java.lang.String tprice) {
		set("tprice", tprice);
		return (M)this;
	}
	
	public java.lang.String getTprice() {
		return getStr("tprice");
	}

	public M setTnumber(java.lang.Integer tnumber) {
		set("tnumber", tnumber);
		return (M)this;
	}
	
	public java.lang.Integer getTnumber() {
		return getInt("tnumber");
	}

	public M setTaddress(java.lang.String taddress) {
		set("taddress", taddress);
		return (M)this;
	}
	
	public java.lang.String getTaddress() {
		return getStr("taddress");
	}

	public M setTcontacts(java.lang.String tcontacts) {
		set("tcontacts", tcontacts);
		return (M)this;
	}
	
	public java.lang.String getTcontacts() {
		return getStr("tcontacts");
	}

	public M setTtime(java.lang.Integer ttime) {
		set("ttime", ttime);
		return (M)this;
	}
	
	public java.lang.Integer getTtime() {
		return getInt("ttime");
	}

	public M setTsum(java.lang.String tsum) {
		set("tsum", tsum);
		return (M)this;
	}
	
	public java.lang.String getTsum() {
		return getStr("tsum");
	}

}
