package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFeedback<M extends BaseFeedback<M>> extends Model<M> implements IBean {

	public M setFeedbackId(java.lang.String feedbackId) {
		set("feedback_id", feedbackId);
		return (M)this;
	}
	
	public java.lang.String getFeedbackId() {
		return getStr("feedback_id");
	}

	public M setFeedbackComments(java.lang.String feedbackComments) {
		set("feedback_comments", feedbackComments);
		return (M)this;
	}
	
	public java.lang.String getFeedbackComments() {
		return getStr("feedback_comments");
	}

	public M setFeedbackPeople(java.lang.Integer feedbackPeople) {
		set("feedback_people", feedbackPeople);
		return (M)this;
	}
	
	public java.lang.Integer getFeedbackPeople() {
		return getInt("feedback_people");
	}

	public M setFeedbackAdvise(java.lang.Integer feedbackAdvise) {
		set("feedback_advise", feedbackAdvise);
		return (M)this;
	}
	
	public java.lang.Integer getFeedbackAdvise() {
		return getInt("feedback_advise");
	}

	public M setFeedbackQuality(java.lang.Integer feedbackQuality) {
		set("feedback_quality", feedbackQuality);
		return (M)this;
	}
	
	public java.lang.Integer getFeedbackQuality() {
		return getInt("feedback_quality");
	}

}
