package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTbPactRent<M extends BaseTbPactRent<M>> extends Model<M> implements IBean {

	public M setPreId(java.lang.Integer preId) {
		set("pre_id", preId);
		return (M)this;
	}
	
	public java.lang.Integer getPreId() {
		return getInt("pre_id");
	}

	public M setMid(java.lang.Integer mid) {
		set("mid", mid);
		return (M)this;
	}
	
	public java.lang.Integer getMid() {
		return getInt("mid");
	}

	public M setTid(java.lang.Integer tid) {
		set("tid", tid);
		return (M)this;
	}
	
	public java.lang.Integer getTid() {
		return getInt("tid");
	}

	public M setPreStime(java.util.Date preStime) {
		set("pre_stime", preStime);
		return (M)this;
	}
	
	public java.util.Date getPreStime() {
		return get("pre_stime");
	}

	public M setPreEtime(java.util.Date preEtime) {
		set("pre_etime", preEtime);
		return (M)this;
	}
	
	public java.util.Date getPreEtime() {
		return get("pre_etime");
	}

	public M setPreState(java.lang.Boolean preState) {
		set("pre_state", preState);
		return (M)this;
	}
	
	public java.lang.Boolean getPreState() {
		return get("pre_state");
	}

	public M setPreNumber(java.lang.Integer preNumber) {
		set("pre_number", preNumber);
		return (M)this;
	}
	
	public java.lang.Integer getPreNumber() {
		return getInt("pre_number");
	}

	public M setPreMoney(java.lang.Float preMoney) {
		set("pre_money", preMoney);
		return (M)this;
	}
	
	public java.lang.Float getPreMoney() {
		return getFloat("pre_money");
	}

}
