package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWxMenu1<M extends BaseWxMenu1<M>> extends Model<M> implements IBean {

	public M setWxMenu1Id(java.lang.Integer wxMenu1Id) {
		set("wx_menu1_id", wxMenu1Id);
		return (M)this;
	}
	
	public java.lang.Integer getWxMenu1Id() {
		return getInt("wx_menu1_id");
	}

	public M setWxMenu1Name(java.lang.String wxMenu1Name) {
		set("wx_menu1_name", wxMenu1Name);
		return (M)this;
	}
	
	public java.lang.String getWxMenu1Name() {
		return getStr("wx_menu1_name");
	}

}
