package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseShop<M extends BaseShop<M>> extends Model<M> implements IBean {

	public M setShopId(java.lang.String shopId) {
		set("shop_id", shopId);
		return (M)this;
	}
	
	public java.lang.String getShopId() {
		return getStr("shop_id");
	}

	public M setShopLot(java.lang.Integer shopLot) {
		set("shop_lot", shopLot);
		return (M)this;
	}
	
	public java.lang.Integer getShopLot() {
		return getInt("shop_lot");
	}

	public M setEndTime(java.util.Date endTime) {
		set("end_time", endTime);
		return (M)this;
	}
	
	public java.util.Date getEndTime() {
		return get("end_time");
	}

	public M setShopCount(java.lang.Integer shopCount) {
		set("shop_count", shopCount);
		return (M)this;
	}
	
	public java.lang.Integer getShopCount() {
		return getInt("shop_count");
	}

	public M setShopIstaocan(java.lang.Boolean shopIstaocan) {
		set("shop_istaocan", shopIstaocan);
		return (M)this;
	}
	
	public java.lang.Boolean getShopIstaocan() {
		return get("shop_istaocan");
	}

	public M setShopOn(java.lang.Boolean shopOn) {
		set("shop_on", shopOn);
		return (M)this;
	}
	
	public java.lang.Boolean getShopOn() {
		return get("shop_on");
	}

	public M setShopPrice(java.lang.Float shopPrice) {
		set("shop_price", shopPrice);
		return (M)this;
	}
	
	public java.lang.Float getShopPrice() {
		return getFloat("shop_price");
	}

}
