package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDispatch<M extends BaseDispatch<M>> extends Model<M> implements IBean {

	public M setPacId(java.lang.String pacId) {
		set("pac_id", pacId);
		return (M)this;
	}
	
	public java.lang.String getPacId() {
		return getStr("pac_id");
	}

	public M setMid(java.lang.String mid) {
		set("mid", mid);
		return (M)this;
	}
	
	public java.lang.String getMid() {
		return getStr("mid");
	}

	public M setServiceOrderId(java.lang.String serviceOrderId) {
		set("service_order_id", serviceOrderId);
		return (M)this;
	}
	
	public java.lang.String getServiceOrderId() {
		return getStr("service_order_id");
	}

	public M setPacStime(java.util.Date pacStime) {
		set("pac_stime", pacStime);
		return (M)this;
	}
	
	public java.util.Date getPacStime() {
		return get("pac_stime");
	}

	public M setPacEtime(java.util.Date pacEtime) {
		set("pac_etime", pacEtime);
		return (M)this;
	}
	
	public java.util.Date getPacEtime() {
		return get("pac_etime");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public M setFatId(java.lang.String fatId) {
		set("fat_id", fatId);
		return (M)this;
	}
	
	public java.lang.String getFatId() {
		return getStr("fat_id");
	}

}
