package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseServiceConfirm<M extends BaseServiceConfirm<M>> extends Model<M> implements IBean {

	public M setServiceConfirmId(java.lang.Integer serviceConfirmId) {
		set("service_confirm_id", serviceConfirmId);
		return (M)this;
	}
	
	public java.lang.Integer getServiceConfirmId() {
		return getInt("service_confirm_id");
	}

	public M setServiceOrderId(java.lang.Integer serviceOrderId) {
		set("service_order_id", serviceOrderId);
		return (M)this;
	}
	
	public java.lang.Integer getServiceOrderId() {
		return getInt("service_order_id");
	}

	public M setUserOpenid(java.lang.String userOpenid) {
		set("user_openid", userOpenid);
		return (M)this;
	}
	
	public java.lang.String getUserOpenid() {
		return getStr("user_openid");
	}

	public M setServiceConfirmDescription(java.lang.String serviceConfirmDescription) {
		set("service_confirm_description", serviceConfirmDescription);
		return (M)this;
	}
	
	public java.lang.String getServiceConfirmDescription() {
		return getStr("service_confirm_description");
	}

	public M setServiceConfirmCount(java.lang.Integer serviceConfirmCount) {
		set("service_confirm_count", serviceConfirmCount);
		return (M)this;
	}
	
	public java.lang.Integer getServiceConfirmCount() {
		return getInt("service_confirm_count");
	}

	public M setQ(java.lang.String q) {
		set("q", q);
		return (M)this;
	}
	
	public java.lang.String getQ() {
		return getStr("q");
	}

}
