package com.o2o.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTechnology<M extends BaseTechnology<M>> extends Model<M> implements IBean {

	public M setFatId(java.lang.String fatId) {
		set("fat_id", fatId);
		return (M)this;
	}
	
	public java.lang.String getFatId() {
		return getStr("fat_id");
	}

	public M setFatName(java.lang.String fatName) {
		set("fat_name", fatName);
		return (M)this;
	}
	
	public java.lang.String getFatName() {
		return getStr("fat_name");
	}

	public M setFatPrice(java.lang.Float fatPrice) {
		set("fat_price", fatPrice);
		return (M)this;
	}
	
	public java.lang.Float getFatPrice() {
		return getFloat("fat_price");
	}

	public M setFatSdate(java.util.Date fatSdate) {
		set("fat_sdate", fatSdate);
		return (M)this;
	}
	
	public java.util.Date getFatSdate() {
		return get("fat_sdate");
	}

	public M setFatContacts(java.lang.String fatContacts) {
		set("fat_contacts", fatContacts);
		return (M)this;
	}
	
	public java.lang.String getFatContacts() {
		return getStr("fat_contacts");
	}

	public M setFatPhone(java.lang.String fatPhone) {
		set("fat_phone", fatPhone);
		return (M)this;
	}
	
	public java.lang.String getFatPhone() {
		return getStr("fat_phone");
	}

	public M setFatPlace(java.lang.String fatPlace) {
		set("fat_place", fatPlace);
		return (M)this;
	}
	
	public java.lang.String getFatPlace() {
		return getStr("fat_place");
	}

	public M setFatEdate(java.util.Date fatEdate) {
		set("fat_edate", fatEdate);
		return (M)this;
	}
	
	public java.util.Date getFatEdate() {
		return get("fat_edate");
	}

	public M setFatState(java.lang.String fatState) {
		set("fat_state", fatState);
		return (M)this;
	}
	
	public java.lang.String getFatState() {
		return getStr("fat_state");
	}

	public M setDescrption(java.lang.String descrption) {
		set("descrption", descrption);
		return (M)this;
	}
	
	public java.lang.String getDescrption() {
		return getStr("descrption");
	}

	public M setServiceOrderId(java.lang.String serviceOrderId) {
		set("service_order_id", serviceOrderId);
		return (M)this;
	}
	
	public java.lang.String getServiceOrderId() {
		return getStr("service_order_id");
	}

	public M setImg(java.lang.String img) {
		set("img", img);
		return (M)this;
	}
	
	public java.lang.String getImg() {
		return getStr("img");
	}

}
