package com.o2o.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_base_manager", "id", Manager.class);
		arp.addMapping("tb_goods", "id", TbGoods.class);
		arp.addMapping("tb_mplace", "id", TbMplace.class);
		arp.addMapping("tb_mstaff", "id", TbMstaff.class);
		arp.addMapping("tb_mtools", "id", TbMtools.class);
		arp.addMapping("tb_muser", "mid", TbMuser.class);
		arp.addMapping("tb_user", "openid", TbUser.class);
	}
}

