package com.o2o.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_base_message", "message_id", Message.class);
		arp.addMapping("tb_city", "city_id", City.class);
		arp.addMapping("tb_dispatch", "pac_id", Dispatch.class);
/*		arp.addMapping("tb_dispatch_qiang", "pacq_id", DispatchQiang.class);*/
		arp.addMapping("tb_district", "district_id", District.class);
		arp.addMapping("tb_feedback", "feedback_id", Feedback.class);
		arp.addMapping("tb_first_type", "first_type_id", Firsttype.class);
		arp.addMapping("tb_goodsinfo", "goodsinfo_id", Goodsinfo.class);
		arp.addMapping("tb_muser", "mid", Muser.class);
		arp.addMapping("tb_order", "order_id", Order.class);
		arp.addMapping("tb_order_detail", "order_detail_id", OrderDetail.class);
		arp.addMapping("tb_pact_employ", "pem_id", PactEmploy.class);
		arp.addMapping("tb_pact_factory", "pfa_id", PactFactory.class);
		arp.addMapping("tb_pact_rent", "pre_id", PactRent.class);
		arp.addMapping("tb_paigong_order", "forward_id", PaigongOrder.class);
		arp.addMapping("tb_province", "province_id", Province.class);
		arp.addMapping("tb_realshop", "realshop_id", Realshop.class);
		arp.addMapping("tb_recruit_info", "rid", RecruitInfo.class);
		arp.addMapping("tb_rent_factory", "pid", RentFactory.class);
		arp.addMapping("tb_rent_tools", "tid", RentTools.class);
		arp.addMapping("tb_sec_type", "sec_type_id", Sectype.class);
		arp.addMapping("tb_service", "service_id", Service.class);
		arp.addMapping("tb_service_confirm", "service_confirm_id", ServiceConfirm.class);
		arp.addMapping("tb_service_order", "service_order_id", ServiceOrder.class);
		arp.addMapping("tb_shangjiaoperation", "shop_goods_id", Shangjiaoperation.class);
		arp.addMapping("tb_shop", "shop_id", Shop.class);
		arp.addMapping("tb_shopcar", "shopcar_id", Shopcar.class);
		arp.addMapping("tb_taocan", "tao_good_id", Taocan.class);
		arp.addMapping("tb_technology", "fat_id", Technology.class);
		arp.addMapping("tb_user", "user_openid", User.class);
		arp.addMapping("tb_base_manager", "id",Manager.class);
		arp.addMapping("tb_base_navigation", "id",Navigation.class);
		arp.addMapping("tb_base_role","id",Role.class);
		arp.addMapping("tb_base_manager_role", "id",ManagerRole.class);
		arp.addMapping("tb_base_role_navigation","id",RoleNavigation.class);
		arp.addMapping("tb_points_gift","points_gift_id",PointsGift.class);
		arp.addMapping("tb_point_record", "point_record_id",PointRecord.class);
	}
}

