package com.o2o.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("tb_base_firsttype", "first_type_id", Firsttype.class);
		arp.addMapping("tb_base_goodsinfo", "goodsinfo_id", Goodsinfo.class);
		arp.addMapping("tb_base_manager", "id", Manager.class);
		arp.addMapping("tb_base_manager_role", "id", ManagerRole.class);
		arp.addMapping("tb_base_navigation", "id", Navigation.class);
		arp.addMapping("tb_base_role", "id", Role.class);
		arp.addMapping("tb_base_role_navigation", "id", RoleNavigation.class);
		arp.addMapping("tb_base_sectype", "sec_type_id", Sectype.class);
		arp.addMapping("tb_base_user", "user_openid", User.class);
	}
}

