package com.o2o.common.model;

import com.o2o.common.model.base.BaseAnnouncement;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Announcement extends BaseAnnouncement<Announcement> {
	public static final Announcement dao = new Announcement().dao();
}
