package com.o2o.common.model;

import com.o2o.common.model.base.BaseBaseMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseMessage extends BaseBaseMessage<BaseMessage> {
	public static final BaseMessage dao = new BaseMessage().dao();
}
