package com.o2o.common.model;

import com.o2o.common.model.base.BaseCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class City extends BaseCity<City> {
	public static final City dao = new City().dao();
}
