package com.o2o.common.model;

import com.o2o.common.model.base.BaseDispatchQiang;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DispatchQiang extends BaseDispatchQiang<DispatchQiang> {
	public static final DispatchQiang dao = new DispatchQiang().dao();
}
