package com.o2o.common.model;

import com.o2o.common.model.base.BaseDispatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dispatch extends BaseDispatch<Dispatch> {
	public static final Dispatch dao = new Dispatch().dao();
}
