package com.o2o.common.model;


import com.o2o.common.model.base.BaseFirsttype;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Firsttype extends BaseFirsttype<Firsttype> {
	public static final Firsttype dao = new Firsttype().dao();
}
