package com.o2o.common.model;

import com.o2o.common.model.base.BaseGoodsinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Goodsinfo extends BaseGoodsinfo<Goodsinfo> {
	public static final Goodsinfo dao = new Goodsinfo().dao();
	
}
