package com.o2o.common.model;

import com.o2o.common.model.base.BaseManager;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Manager extends BaseManager<Manager> {
	public static final Manager dao = new Manager().dao();
}
