package com.o2o.common.model;

import com.o2o.common.model.base.BaseManagerRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ManagerRole extends BaseManagerRole<ManagerRole> {
	public static final ManagerRole dao = new ManagerRole().dao();
}
