package com.o2o.common.model;

import com.o2o.common.model.base.BaseMuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Muser extends BaseMuser<Muser> {
	public static final Muser dao = new Muser().dao();
}
