package com.o2o.common.model;

import com.o2o.common.model.base.BaseNavigation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Navigation extends BaseNavigation<Navigation> {
	public static final Navigation dao = new Navigation().dao();
}
