package com.o2o.common.model;

import com.o2o.common.model.base.BaseOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderDetail extends BaseOrderDetail<OrderDetail> {
	public static final OrderDetail dao = new OrderDetail().dao();
}
