package com.o2o.common.model;

import com.o2o.common.model.base.BasePactRent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PactRent extends BasePactRent<PactRent> {
	public static final PactRent dao = new PactRent().dao();
}
