package com.o2o.common.model;

import com.o2o.common.model.base.BasePactFactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PactFactory extends BasePactFactory<PactFactory> {
	public static final PactFactory dao = new PactFactory().dao();
}
