package com.o2o.common.model;

import com.o2o.common.model.base.BasePactEmploy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PactEmploy extends BasePactEmploy<PactEmploy> {
	public static final PactEmploy dao = new PactEmploy().dao();
}
