package com.o2o.common.model;

import com.o2o.common.model.base.BasePaigongOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaigongOrder extends BasePaigongOrder<PaigongOrder> {
	public static final PaigongOrder dao = new PaigongOrder().dao();
}
