package com.o2o.common.model;

import com.o2o.common.model.base.BasePointRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointRecord extends BasePointRecord<PointRecord> {
	public static final PointRecord dao = new PointRecord().dao();
}
