package com.o2o.common.model;

import com.o2o.common.model.base.BasePointsGift;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PointsGift extends BasePointsGift<PointsGift> {
	public static final PointsGift dao = new PointsGift().dao();
}
