package com.o2o.common.model;

import com.o2o.common.model.base.BaseProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Province extends BaseProvince<Province> {
	public static final Province dao = new Province().dao();
}
