package com.o2o.common.model;

import com.o2o.common.model.base.BaseRealshop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Realshop extends BaseRealshop<Realshop> {
	public static final Realshop dao = new Realshop().dao();
}
