package com.o2o.common.model;

import com.o2o.common.model.base.BaseRecruitInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RecruitInfo extends BaseRecruitInfo<RecruitInfo> {
	public static final RecruitInfo dao = new RecruitInfo().dao();
}
