package com.o2o.common.model;

import com.o2o.common.model.base.BaseRentFactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RentFactory extends BaseRentFactory<RentFactory> {
	public static final RentFactory dao = new RentFactory().dao();
}
