package com.o2o.common.model;

import com.o2o.common.model.base.BaseRentTools;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RentTools extends BaseRentTools<RentTools> {
	public static final RentTools dao = new RentTools().dao();
}
