package com.o2o.common.model;

import com.o2o.common.model.base.BaseRoleNavigation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RoleNavigation extends BaseRoleNavigation<RoleNavigation> {
	public static final RoleNavigation dao = new RoleNavigation().dao();
}
