package com.o2o.common.model;

import com.o2o.common.model.base.BaseSectype;


/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Sectype extends BaseSectype<Sectype> {
	public static final Sectype dao = new Sectype().dao();
}
