package com.o2o.common.model;

import com.o2o.common.model.base.BaseService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Service extends BaseService<Service> {
	public static final Service dao = new Service().dao();
}
