package com.o2o.common.model;

import com.o2o.common.model.base.BaseServiceConfirm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServiceConfirm extends BaseServiceConfirm<ServiceConfirm> {
	public static final ServiceConfirm dao = new ServiceConfirm().dao();
}
