package com.o2o.common.model;

import com.o2o.common.model.base.BaseServiceOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServiceOrder extends BaseServiceOrder<ServiceOrder> {
	public static final ServiceOrder dao = new ServiceOrder().dao();
}
