package com.o2o.common.model;

import com.o2o.common.model.base.BaseShangjiaoperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shangjiaoperation extends BaseShangjiaoperation<Shangjiaoperation> {
	public static final Shangjiaoperation dao = new Shangjiaoperation().dao();
}
