package com.o2o.common.model;

import com.o2o.common.model.base.BaseShopcar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shopcar extends BaseShopcar<Shopcar> {
	public static final Shopcar dao = new Shopcar().dao();
}
