package com.o2o.common.model;

import com.o2o.common.model.base.BaseShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Shop extends BaseShop<Shop> {
	public static final Shop dao = new Shop().dao();
}
