package com.o2o.common.model;

import com.o2o.common.model.base.BaseTaocan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Taocan extends BaseTaocan<Taocan> {
	public static final Taocan dao = new Taocan().dao();
}
