package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbCity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbCity extends BaseTbCity<TbCity> {
	public static final TbCity dao = new TbCity().dao();
}
