package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbDispatchQiang;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDispatchQiang extends BaseTbDispatchQiang<TbDispatchQiang> {
	public static final TbDispatchQiang dao = new TbDispatchQiang().dao();
}
