package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbDistrict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDistrict extends BaseTbDistrict<TbDistrict> {
	public static final TbDistrict dao = new TbDistrict().dao();
}
