package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbDispatch;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbDispatch extends BaseTbDispatch<TbDispatch> {
	public static final TbDispatch dao = new TbDispatch().dao();
}
