package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbFeedback extends BaseTbFeedback<TbFeedback> {
	public static final TbFeedback dao = new TbFeedback().dao();
}
