package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbFirstType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbFirstType extends BaseTbFirstType<TbFirstType> {
	public static final TbFirstType dao = new TbFirstType().dao();
}
