package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbGoodsinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbGoodsinfo extends BaseTbGoodsinfo<TbGoodsinfo> {
	public static final TbGoodsinfo dao = new TbGoodsinfo().dao();
}
