package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbGoods;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbGoods extends BaseTbGoods<TbGoods> {
	public static final TbGoods dao = new TbGoods().dao();
}
