package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbMplace;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMplace extends BaseTbMplace<TbMplace> {
	public static final TbMplace dao = new TbMplace().dao();
}
