package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbMstaff;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMstaff extends BaseTbMstaff<TbMstaff> {
	public static final TbMstaff dao = new TbMstaff().dao();
}
