package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbMtools;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMtools extends BaseTbMtools<TbMtools> {
	public static final TbMtools dao = new TbMtools().dao();
}
