package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbMuser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbMuser extends BaseTbMuser<TbMuser> {
	public static final TbMuser dao = new TbMuser().dao();
}
