package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOrder extends BaseTbOrder<TbOrder> {
	public static final TbOrder dao = new TbOrder().dao();
}
