package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbOrderDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbOrderDetail extends BaseTbOrderDetail<TbOrderDetail> {
	public static final TbOrderDetail dao = new TbOrderDetail().dao();
}
