package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbPactRent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPactRent extends BaseTbPactRent<TbPactRent> {
	public static final TbPactRent dao = new TbPactRent().dao();
}
