package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbPactFactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPactFactory extends BaseTbPactFactory<TbPactFactory> {
	public static final TbPactFactory dao = new TbPactFactory().dao();
}
