package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbPactEmploy;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPactEmploy extends BaseTbPactEmploy<TbPactEmploy> {
	public static final TbPactEmploy dao = new TbPactEmploy().dao();
}
