package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbPaigongOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbPaigongOrder extends BaseTbPaigongOrder<TbPaigongOrder> {
	public static final TbPaigongOrder dao = new TbPaigongOrder().dao();
}
