package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbProvince;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbProvince extends BaseTbProvince<TbProvince> {
	public static final TbProvince dao = new TbProvince().dao();
}
