package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbRealshop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRealshop extends BaseTbRealshop<TbRealshop> {
	public static final TbRealshop dao = new TbRealshop().dao();
}
