package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbRecruitInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRecruitInfo extends BaseTbRecruitInfo<TbRecruitInfo> {
	public static final TbRecruitInfo dao = new TbRecruitInfo().dao();
}
