package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbRentTools;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRentTools extends BaseTbRentTools<TbRentTools> {
	public static final TbRentTools dao = new TbRentTools().dao();
}
