package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbRentFactory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbRentFactory extends BaseTbRentFactory<TbRentFactory> {
	public static final TbRentFactory dao = new TbRentFactory().dao();
}
