package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbServiceConfirm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbServiceConfirm extends BaseTbServiceConfirm<TbServiceConfirm> {
	public static final TbServiceConfirm dao = new TbServiceConfirm().dao();
}
