package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbService;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbService extends BaseTbService<TbService> {
	public static final TbService dao = new TbService().dao();
}
