package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbServiceOrder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbServiceOrder extends BaseTbServiceOrder<TbServiceOrder> {
	public static final TbServiceOrder dao = new TbServiceOrder().dao();
}
