package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbSecType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbSecType extends BaseTbSecType<TbSecType> {
	public static final TbSecType dao = new TbSecType().dao();
}
