package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbShangjiaoperation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShangjiaoperation extends BaseTbShangjiaoperation<TbShangjiaoperation> {
	public static final TbShangjiaoperation dao = new TbShangjiaoperation().dao();
}
