package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbShop;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShop extends BaseTbShop<TbShop> {
	public static final TbShop dao = new TbShop().dao();
}
