package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbShopcar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbShopcar extends BaseTbShopcar<TbShopcar> {
	public static final TbShopcar dao = new TbShopcar().dao();
}
