package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbTaocan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTaocan extends BaseTbTaocan<TbTaocan> {
	public static final TbTaocan dao = new TbTaocan().dao();
}
