package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbTechnology;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbTechnology extends BaseTbTechnology<TbTechnology> {
	public static final TbTechnology dao = new TbTechnology().dao();
}
