package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbUser extends BaseTbUser<TbUser> {
	public static final TbUser dao = new TbUser().dao();
}
