package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbWxMenu1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbWxMenu1 extends BaseTbWxMenu1<TbWxMenu1> {
	public static final TbWxMenu1 dao = new TbWxMenu1().dao();
}
