package com.o2o.common.model;

import com.o2o.common.model.base.BaseTbWxMenu2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TbWxMenu2 extends BaseTbWxMenu2<TbWxMenu2> {
	public static final TbWxMenu2 dao = new TbWxMenu2().dao();
}
