package com.o2o.common.model;

import com.o2o.common.model.base.BaseTechnology;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Technology extends BaseTechnology<Technology> {
	public static final Technology dao = new Technology().dao();
}
