package com.o2o.common.model;

import com.o2o.common.model.base.BaseWxMenu2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxMenu2 extends BaseWxMenu2<WxMenu2> {
	public static final WxMenu2 dao = new WxMenu2().dao();
}
