package com.o2o.common.model;

import com.o2o.common.model.base.BaseWxMenu1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WxMenu1 extends BaseWxMenu1<WxMenu1> {
	public static final WxMenu1 dao = new WxMenu1().dao();
}
